accounts/urls.py
from django.contrib import admin
from django.urls import path, include

from accounts.views import UserRegistrationView, LoginView, LogoutView, ChangePasswordView

app_name = "accounts"
urlpatterns = [
    path("accounts/", include("allauth.urls")),
    path("accounts/signup/", UserRegistrationView.as_view(), name="account_signup"),
    # path("profile/", view=UserDetailView.as_view(), name="profile"),
    # path("update-profile/", view=CandidateCreateView.as_view(), name="update_profile"),
    path("accounts/login/", view=LoginView.as_view(), name="account_login"),
    path("accounts/logout/", view=LogoutView.as_view(), name="account_logout"),
    path('accounts/reset-password/', ChangePasswordView.as_view(), name='reset-password'),

]

chanceofhope/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', TemplateView.as_view(template_name="home.html")),
    path('user', include('accounts.urls')),
# path("accounts/", include("allauth.urls")),
]
if settings.DEBUG:
    from django.conf.urls.static import static
    from django.contrib.staticfiles.urls import staticfiles_urlpatterns

    # serve static and media files from development server
    urlpatterns += staticfiles_urlpatterns()
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/home.html
{% load static socialaccount %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Home page</title>
</head>
<body>
 {% if request.user.is_authenticated %}
Hello {{ request.user.username }}
     <a href="{% url "accounts:reset-password" %}"> Reset Password </a>
{% else %}
Hello Anonymous
     <a href="{% url "accounts:account_signup" %}"> Register </a>
          <a href="{% provider_login_url "google" method="oauth2" %}">
                                                        <img src="{% static "images/google-icon.png" %}"
                                                             style="margin-left: 10px" alt="" width="22" height="22">
                                                    </a>
{% endif %}
</body>
</html>